name: Flutter CI

# <-- THESE ARE THE TRIGGERS
on:
  workflow_dispatch:    # lets you manually trigger the workflow
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - run: flutter pub get

      - run: flutter test
